name: crossroads_events
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  animated_background: ^1.0.5
  async: ^2.3.0
  image_crop: ^0.3.1
  image_picker: ^0.6.1+8
  scoped_model: ^1.0.1
  bloc: ^2.0.0
  photo_view: ^0.9.0
  giphy_picker: ^1.0.0
  flutter_bloc: ^2.0.0
  flutter_local_notifications: ^0.8.4+3
  path_provider: ^1.4.5
  badges: ^1.1.0
  audioplayers: ^0.13.5
  bubbled_navigation_bar: ^0.0.4
  flutter_custom_clippers: ^1.1.0
  flutter_custom_dialog: ^1.0.13
  flutter_inner_drawer: ^0.5.2
  flutter_swiper : ^1.1.6
  flutter_page_indicator: ^0.0.3
  fluttertoast: ^3.1.3
  transformer_page_view: ^0.1.6
  cached_network_image: ^2.0.0-rc
  add_2_calendar: ^1.3.0
  flutter_facebook_login: ^2.0.1
  cloud_firestore: ^0.12.9+3
  google_sign_in: ^4.0.7
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.1
  firebase_analytics: ^5.0.6
  firebase_storage: ^3.0.8
  firebase_messaging: ^6.0.2
  rxdart: ^0.22.2
  gradient_widgets: ^0.5.0
  flutter_form_builder: ^3.5.5
  keyboard_actions: ^2.1.2
  smart_flare: ^0.2.8
  flare_flutter: ^1.6.2
  provider: ^3.1.0
  font_awesome_flutter: ^8.5.0
  stripe_payment: ^1.0.5
  cloud_functions: ^0.4.1+4
  fl_chart: ^0.3.4



  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/test.png
    - assets/img/normal_user_icon.png
    - assets/animation/drawer.flr
    - assets/img/img_not_available.jpeg
    - assets/audio/you-have-new-message.mp3
    - assets/audio/i-demand-attention.mp3
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: CupertinoIcons
      fonts:
        - asset: assets/fonts/cupertino/CupertinoIcons.ttf
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
